using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrozzleApp.Classes
{
    class Crozzle
    {
        /*
         * 
         */

        // Configuraton file.
        private string configFile;

        // Word list file.
        private string wordListFile;

        Configuration configuration;

        Words wordList;

        Grid grid;

        /* 
         * Crozzle Size.
         * The number of rows and columns.
         * It must be generated by Grid.
        */
        private int rows;
        private int columns;

        public int Rows { get => rows; private set => CheckNumber(value); }
        public int Columns { get => columns; private set => CheckNumber(value); }

        //OpenFileDialog pass TXT as a parameter in Crozzle class

        public Crozzle(string file)
        {
            ReadFile(file);
            configuration = new Configuration(configFile);
            wordList = new Words(wordListFile);
            grid = new Grid(rows, columns);
        }

        private int CheckNumber(int value)
        {
            if ((value.GetType() == typeof(int)) && (value > 0))
            {
                return value;
            }
            else
            {
                return -1;
            }
        }

        #region CROZZLE METHODS
        private void ReadFile(string file)
        {

            ValidateFile();
        }

        private void ValidateFile()
        {

        }

        private void ValidadeCrozzle()
        {

        }
        #endregion
    }
}
